matrix:
  include:
    - dist: bionic
      arch: ppc64le
    - dist: xenial
      arch: ppc64le
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - openjdk13
script:
  - java -version
  - echo ${TRAVIS_CPU_ARCH}
