language: java
arch: ppc64le
matrix:
  include:
    - env: ENV=bionic-JDK8
      dist: bionic
      jdk: openjdk8
    - env: ENV=bionic-JDK11
      dist: bionic
      jdk: openjdk11
    - env: ENV=bionic-JDK12
      dist: bionic
      jdk: openjdk12
    - env: ENV=bionic-JDK13
      dist: bionic
      jdk: openjdk13
    - env: ENV=xenial-JDK8
      dist: xenial
      jdk: openjdk8
    - env: ENV=xenial-JDK11
      dist: xenial
      jdk: openjdk11
    - env: ENV=xenial-JDK12
      dist: xenial
      jdk: openjdk12
    - env: ENV=xenial-JDK13
      dist: xenial
      jdk: openjdk13

script:
  - java -version
  - echo ${TRAVIS_CPU_ARCH}
