matrix:
  include:
   - os: linux
     arch: ppc64le
     dist: bionic
   - os: linux
     arch: ppc64le
     dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - openjdk13
script:
  - java -version
  - echo ${TRAVIS_CPU_ARCH}
