arch: ppc64le
matrix:
  include:
    - env: ENV=bionic
      dist: bionic
    - env: ENV=xenial
      dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - openjdk13
dist: 
  - xenial
  - bionic
script:
  - java -version
  - echo ${TRAVIS_CPU_ARCH}
