#language: java

matrix:
  include:
    - env: ENV=bionic-JDK8
      dist: bionic
      jdk: openjdk8
      arch: s390x
    - env: ENV=bionic-JDK11
      dist: bionic
      jdk: openjdk11
      arch: s390x
    - env: ENV=bionic-JDK12
      dist: bionic
      jdk: openjdk12
      arch: s390x
    - env: ENV=bionic-JDK13
      dist: bionic
      jdk: openjdk13
      arch: s390x
    - env: ENV=xenial-JDK8
      dist: xenial
      jdk: openjdk8
      arch: s390x
    - env: ENV=xenial-JDK11
      dist: xenial
      jdk: openjdk11
      arch: s390x
    - env: ENV=xenial-JDK12
      dist: xenial
      jdk: openjdk12
      arch: s390x
    - env: ENV=xenial-JDK13
      dist: xenial
      jdk: openjdk13
      arch: s390x
    
    - env: ENV=bionic-JDK8
      dist: bionic
      jdk: openjdk8
      arch: ppc64le
    - env: ENV=bionic-JDK11
      dist: bionic
      jdk: openjdk11
      arch: ppc64le
    - env: ENV=bionic-JDK12
      dist: bionic
      jdk: openjdk12
      arch: ppc64le
    - env: ENV=bionic-JDK13
      dist: bionic
      jdk: openjdk13
      arch: ppc64le
    - env: ENV=xenial-JDK8
      dist: xenial
      jdk: openjdk8
      arch: ppc64le
    - env: ENV=xenial-JDK11
      dist: xenial
      jdk: openjdk11
      arch: ppc64le
    - env: ENV=xenial-JDK12
      dist: xenial
      jdk: openjdk12
      arch: ppc64le
    - env: ENV=xenial-JDK13
      dist: xenial
      jdk: openjdk13
      arch: ppc64le

script:
  - java -version
  - echo ${TRAVIS_CPU_ARCH}
